module.exports = {
  domain: process.env.domain,
  clientId: process.env.clientId,
  audience: process.env.audience,
  scopes: [
    'write:aircraft:privileged',
    'read:activity',
    'read:address:privileged',
    'read:aircraft',
    'read:aircraft:all',
    'read:aircraft:privileged',
    'read:authorization',
    'read:contact',
    'read:contact:all',
    'read:operator',
    'read:operator:all',
    'read:operator:privileged',
    'read:person',
    'read:person:all',
    'read:pilot',
    'read:pilot:privileged',
    'read:unthrottled',
    'write:activity',
    'write:address',
    'write:address:privileged',
    'write:aircraft',
    'write:authorization',
    'write:contact',
    'write:operator',
    'write:operator:privileged',
    'write:person',
  ],
};
