module.exports = {
  domain: process.env.domain,
  clientId: process.env.clientId,
  audience: process.env.audience,
  scopes: [
    'read:operator',
    'read:operator:all',
    'read:operator:privilaged',
    'read:person',
    'write:address',
    'write:address:privilaged',
    'write:operator:privilaged',
    'write:operator',
    'write:contact',
    'read:contact:all',
    'read:person:all',
    'read:contact',
    'read:pilot',
    'read:pilot:privilaged',
    'read:address:privilaged',
    'read:aircraft',
    'read:aircraft:privilaged',
    'write:aircraft',
    'write:aircraft:privialged',
  ],
};
